# Generated by Django 6.0.8 on 2026-08-18 07:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال')], default='ACTIVE', max_length=16)),
            ],
            options={
                'db_table': 'pricing_providers',
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='MarketQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price_per_gram', models.DecimalField(decimal_places=2, max_digits=18)),
                ('price_per_mesghal', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='IRR', max_length=3)),
                ('observed_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('quality_status', models.CharField(choices=[('VALID', 'معتبر'), ('STALE', 'قدیمی'), ('REJECTED', 'رد شده')], default='VALID', max_length=16)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='catalog.assettype')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='pricing.pricingprovider')),
            ],
            options={
                'db_table': 'market_quotes',
                'ordering': ['-observed_at'],
                'indexes': [models.Index(fields=['asset_type', '-observed_at'], name='market_quot_asset_t_8c111b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RetailerProductPricing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('labor_fee_type', models.CharField(choices=[('PERCENTAGE', 'درصدی'), ('FIXED_PER_GRAM', 'ثابت به\u200cازای هر گرم')], max_length=20)),
                ('labor_fee_value', models.DecimalField(decimal_places=4, max_digits=14)),
                ('profit_margin_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retailer_pricings', to='catalog.assettype')),
                ('created_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_pricings', to='tenancy.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_pricings', to='tenancy.organization')),
            ],
            options={
                'db_table': 'retailer_product_pricing',
                'indexes': [models.Index(fields=['organization', 'asset_type'], name='retailer_pr_organiz_3c3812_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('effective_to__isnull', True)), fields=('organization', 'asset_type'), name='uniq_active_pricing_per_org_asset')],
            },
        ),
    ]
