# Generated by Django 6.0.8 on 2026-08-16 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization_type', models.CharField(choices=[('RETAILER', 'طلافروشی خرد'), ('BULLION_DEALER', 'بنکدار'), ('WORKSHOP', 'طلاساز')], max_length=32)),
                ('legal_name', models.CharField(max_length=255)),
                ('display_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('PENDING_CONTRACT', 'در انتظار قرارداد'), ('ACTIVE', 'فعال'), ('SUSPENDED', 'معلق')], default='PENDING_CONTRACT', max_length=20)),
                ('onboarded_by_zerva_staff', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'organizations',
                'indexes': [models.Index(fields=['organization_type', 'status'], name='organizatio_organiz_37f825_idx')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationContract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contract_reference', models.CharField(max_length=100)),
                ('signed_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('TERMINATED', 'خاتمه\u200cیافته')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contract', to='tenancy.organization')),
            ],
            options={
                'db_table': 'organization_contracts',
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('membership_role', models.CharField(choices=[('OWNER', 'مالک'), ('STAFF', 'کارمند')], max_length=16)),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('REVOKED', 'لغوشده')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='tenancy.organization')),
            ],
            options={
                'db_table': 'memberships',
                'indexes': [models.Index(fields=['organization', 'status'], name='memberships_organiz_cf8351_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'user'), name='uniq_membership_org_user')],
            },
        ),
    ]
