# Generated by Django 6.0.8 on 2026-08-19 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RfidTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('epc', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('INACTIVE', 'غیرفعال')], default='ACTIVE', max_length=16)),
                ('inventory_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfid_tags', to='inventory.inventoryposition')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfid_tags', to='tenancy.organization')),
            ],
            options={
                'db_table': 'rfid_tags',
            },
        ),
        migrations.CreateModel(
            name='RfidSyncEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('ITEM_DETECTED', 'شناسایی شد'), ('ITEM_MISSING', 'گم شد'), ('ALERT_RAISED', 'هشدار صادر شد')], max_length=16)),
                ('occurred_at', models.DateTimeField()),
                ('raw_payload_ref', models.CharField(blank=True, max_length=255)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfid_sync_events', to='tenancy.organization')),
            ],
            options={
                'db_table': 'rfid_sync_events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['organization', '-occurred_at'], name='rfid_sync_e_organiz_2c81ed_idx')],
            },
        ),
    ]
