# Generated by Django 6.0.8 on 2026-08-16 06:13

import apps.identity.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='KycTierPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tier', models.PositiveSmallIntegerField(unique=True)),
                ('max_grams_per_transaction', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('required_verification', models.CharField(max_length=255)),
                ('description_fa', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'kyc_tier_policies',
                'ordering': ['tier'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_e164', models.CharField(max_length=15, unique=True)),
                ('account_role', models.CharField(choices=[('CONSUMER', 'خریدار'), ('RETAILER_STAFF', 'کارمند طلافروشی'), ('BULLION_DEALER_STAFF', 'کارمند بنکداری'), ('WORKSHOP_STAFF', 'کارمند طلاسازی'), ('ZERVA_ADMIN', 'ادمین زروا')], max_length=32)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('last_name', models.CharField(blank=True, max_length=150)),
                ('national_id', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id_verified', models.BooleanField(default=False)),
                ('national_id_verified_at', models.DateTimeField(blank=True, null=True)),
                ('bank_verified', models.BooleanField(default=False)),
                ('bank_verified_at', models.DateTimeField(blank=True, null=True)),
                ('kyc_level', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('SUSPENDED', 'معلق'), ('DELETED', 'حذف\u200cشده')], default='ACTIVE', max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', apps.identity.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='KycVerificationEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_level', models.PositiveSmallIntegerField()),
                ('provider', models.CharField(choices=[('CIVIL_REGISTRY', 'ثبت\u200cاحوال'), ('BANKING_NETWORK', 'شبکه بانکی')], max_length=32)),
                ('provider_reference', models.CharField(blank=True, max_length=255)),
                ('result', models.CharField(choices=[('PENDING', 'در انتظار'), ('APPROVED', 'تایید شد'), ('REJECTED', 'رد شد'), ('ERROR', 'خطا')], default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_verification_events',
            },
        ),
        migrations.CreateModel(
            name='OtpVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mobile_e164', models.CharField(db_index=True, max_length=15)),
                ('code_hash', models.CharField(max_length=255)),
                ('purpose', models.CharField(choices=[('LOGIN', 'ورود'), ('SIGNUP', 'ثبت\u200cنام')], max_length=16)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('ip_hash', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otp_verifications',
                'indexes': [models.Index(fields=['mobile_e164', 'created_at'], name='otp_verific_mobile__a246fa_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id_verified', True)), fields=('national_id',), name='uniq_verified_national_id'),
        ),
        migrations.AddIndex(
            model_name='kycverificationevent',
            index=models.Index(fields=['user', 'requested_at'], name='kyc_verific_user_id_7459dc_idx'),
        ),
    ]
