# Generated by Django 6.0.8 on 2026-08-28 09:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyKey',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=100)),
                ('request_hash', models.CharField(max_length=64)),
                ('response_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('COMPLETED', 'تکمیل\u200cشده')], default='PENDING', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'idempotency_keys',
                'indexes': [models.Index(fields=['scope', 'expires_at'], name='idempotency_scope_e9d63e_idx')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('aggregate_type', models.CharField(max_length=100)),
                ('aggregate_id', models.UUIDField()),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PROCESSING', 'در حال پردازش'), ('PUBLISHED', 'منتشرشده'), ('FAILED', 'ناموفق')], default='PENDING', max_length=16)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'db_table': 'outbox_events',
                'indexes': [models.Index(fields=['status', 'occurred_at'], name='outbox_even_status_5628cd_idx'), models.Index(fields=['aggregate_type', 'aggregate_id'], name='outbox_even_aggrega_d56a15_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=100)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.UUIDField()),
                ('before_snapshot', models.JSONField(blank=True, null=True)),
                ('after_snapshot', models.JSONField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100)),
                ('correlation_id', models.CharField(blank=True, max_length=100)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('actor_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to='tenancy.membership')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_events',
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_event_entity__1d80e9_idx'), models.Index(fields=['-occurred_at'], name='audit_event_occurre_09de70_idx')],
            },
        ),
    ]
