# Generated by Django 6.0.8 on 2026-08-26 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerRetailerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('SUSPENDED', 'معلق')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bullion_dealer_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dealer_accounts', to='tenancy.organization')),
                ('retailer_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retailer_accounts', to='tenancy.organization')),
            ],
            options={
                'db_table': 'dealer_retailer_accounts',
            },
        ),
        migrations.CreateModel(
            name='DealerRetailerLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('GOLD_WITHDRAWAL', 'برداشت جنس'), ('SETTLEMENT_PAYMENT', 'تسویه'), ('ADJUSTMENT', 'اصلاحیه')], max_length=20)),
                ('grams', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('price_per_gram_at_transaction', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('amount_toman', models.DecimalField(decimal_places=2, max_digits=18)),
                ('occurred_at', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='b2b_ledger.dealerretaileraccount')),
                ('recorded_by_membership', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_dealer_entries', to='tenancy.membership')),
            ],
            options={
                'db_table': 'dealer_retailer_ledger_entries',
            },
        ),
        migrations.CreateModel(
            name='WorkshopPurchaseRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_grams', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('spec_notes', models.TextField(blank=True)),
                ('delivery_status', models.CharField(choices=[('PENDING', 'در انتظار'), ('DELIVERED', 'تحویل شد'), ('NOT_DELIVERED', 'تحویل نشد')], default='PENDING', max_length=16)),
                ('payment_status', models.CharField(choices=[('PENDING', 'در انتظار'), ('PAID', 'پرداخت شد'), ('NOT_PAID', 'پرداخت نشد')], default='PENDING', max_length=16)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('delivery_updated_at', models.DateTimeField(blank=True, null=True)),
                ('payment_updated_at', models.DateTimeField(blank=True, null=True)),
                ('bullion_dealer_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshop_purchase_requests', to='tenancy.organization')),
                ('recorded_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recorded_workshop_requests', to='tenancy.membership')),
                ('workshop_org', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_purchase_requests', to='tenancy.organization')),
            ],
            options={
                'db_table': 'workshop_purchase_requests',
            },
        ),
        migrations.AddConstraint(
            model_name='dealerretaileraccount',
            constraint=models.UniqueConstraint(fields=('bullion_dealer_org', 'retailer_org'), name='uniq_dealer_retailer_pair'),
        ),
        migrations.AddIndex(
            model_name='dealerretailerledgerentry',
            index=models.Index(fields=['account', '-occurred_at'], name='dealer_reta_account_20806f_idx'),
        ),
        migrations.AddIndex(
            model_name='workshoppurchaserequest',
            index=models.Index(fields=['workshop_org', '-requested_at'], name='workshop_pu_worksho_da6e3e_idx'),
        ),
    ]
