# Generated by Django 6.0.8 on 2026-08-19 07:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('available_grams', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('reserved_grams', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('last_synced_from_rfid_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_positions', to='catalog.assettype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_positions', to='tenancy.organization')),
            ],
            options={
                'db_table': 'inventory_positions',
                'constraints': [models.UniqueConstraint(fields=('organization', 'asset_type'), name='uniq_inventory_position_org_asset'), models.CheckConstraint(condition=models.Q(('available_grams__gte', 0)), name='inventory_available_grams_non_negative'), models.CheckConstraint(condition=models.Q(('reserved_grams__gte', 0)), name='inventory_reserved_grams_non_negative')],
            },
        ),
    ]
