# Generated by Django 6.0.8 on 2026-08-23 10:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('tenancy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoldAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('FROZEN', 'مسدود')], default='ACTIVE', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='gold_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gold_accounts',
            },
        ),
        migrations.CreateModel(
            name='GoldAccountRetailerPosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance_grams', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('available_grams', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('reserved_grams', models.DecimalField(decimal_places=6, default=0, max_digits=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_gold_positions', to='catalog.assettype')),
                ('gold_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retailer_positions', to='ledger.goldaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_gold_positions', to='tenancy.organization')),
            ],
            options={
                'db_table': 'gold_account_retailer_positions',
            },
        ),
        migrations.CreateModel(
            name='GoldLedgerTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('BUYER_PURCHASE', 'خرید خریدار'), ('BUYER_SALE', 'فروش خریدار'), ('ADJUSTMENT', 'اصلاحیه')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'gold_ledger_transactions',
                'indexes': [models.Index(fields=['transaction_type', '-occurred_at'], name='gold_ledger_transac_fe91ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='GoldLedgerLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('CREDIT', 'بستانکار'), ('DEBIT', 'بدهکار')], max_length=10)),
                ('grams', models.DecimalField(decimal_places=6, max_digits=18)),
                ('price_per_gram_snapshot', models.DecimalField(decimal_places=2, max_digits=18)),
                ('amount_toman', models.DecimalField(decimal_places=2, max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gold_account_retailer_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_lines', to='ledger.goldaccountretailerposition')),
                ('ledger_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='ledger.goldledgertransaction')),
            ],
            options={
                'db_table': 'gold_ledger_lines',
            },
        ),
        migrations.AddConstraint(
            model_name='goldaccountretailerposition',
            constraint=models.UniqueConstraint(fields=('gold_account', 'organization', 'asset_type'), name='uniq_position_per_account_org_asset'),
        ),
        migrations.AddConstraint(
            model_name='goldledgerline',
            constraint=models.CheckConstraint(condition=models.Q(('grams__gt', 0)), name='ledger_line_grams_positive'),
        ),
    ]
