# Generated by Django 6.0.8 on 2026-08-24 19:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
        ('ledger', '0001_initial'),
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoApprovalPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('max_auto_approve_grams', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('price_tolerance_percentage', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('price_growth_rate_threshold', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='auto_approval_policies', to='tenancy.organization')),
            ],
            options={
                'db_table': 'auto_approval_policies',
            },
        ),
        migrations.CreateModel(
            name='BuyerOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction', models.CharField(choices=[('BUY', 'خرید'), ('SELL', 'فروش')], max_length=4)),
                ('input_mode', models.CharField(choices=[('TOMAN_TO_GRAM', 'ریال به گرم'), ('GRAM_TO_TOMAN', 'گرم به ریال')], max_length=20)),
                ('requested_toman_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('requested_grams', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('price_per_gram_snapshot', models.DecimalField(decimal_places=2, max_digits=18)),
                ('computed_grams', models.DecimalField(decimal_places=6, max_digits=18)),
                ('computed_toman_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('kyc_tier_at_request', models.PositiveSmallIntegerField()),
                ('kyc_check_result', models.CharField(choices=[('PASSED', 'قبول'), ('FAILED_LIMIT', 'رد به\u200cدلیل سقف')], max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'پیش\u200cنویس'), ('RESERVED', 'رزرو شده'), ('AUTO_APPROVED', 'تایید خودکار'), ('REJECTED', 'رد شده'), ('EXPIRED', 'منقضی شده'), ('COMPLETED', 'تکمیل شده')], default='DRAFT', max_length=16)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_orders', to='catalog.assettype')),
                ('gold_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='ledger.goldaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_orders', to='tenancy.organization')),
                ('performed_by_membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handled_orders', to='tenancy.membership')),
            ],
            options={
                'db_table': 'buyer_orders',
            },
        ),
        migrations.CreateModel(
            name='InternalInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('grams', models.DecimalField(decimal_places=6, max_digits=18)),
                ('amount_toman', models.DecimalField(decimal_places=2, max_digits=18)),
                ('issued_at', models.DateTimeField()),
                ('is_fiscal_authority_submitted', models.BooleanField(default=False)),
                ('buyer_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='invoice', to='consumer.buyerorder')),
                ('gold_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='ledger.goldaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_invoices', to='tenancy.organization')),
            ],
            options={
                'db_table': 'internal_invoices',
            },
        ),
        migrations.CreateModel(
            name='OrderReservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reserved_grams', models.DecimalField(decimal_places=6, max_digits=18)),
                ('status', models.CharField(choices=[('ACTIVE', 'فعال'), ('RELEASED', 'آزادشده'), ('CONVERTED', 'تبدیل\u200cشده')], default='ACTIVE', max_length=16)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='reservation', to='consumer.buyerorder')),
                ('gold_account_retailer_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_reservations', to='ledger.goldaccountretailerposition')),
                ('inventory_position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_reservations', to='inventory.inventoryposition')),
            ],
            options={
                'db_table': 'order_reservations',
            },
        ),
        migrations.AddIndex(
            model_name='buyerorder',
            index=models.Index(fields=['organization', '-created_at'], name='buyer_order_organiz_10e225_idx'),
        ),
        migrations.AddIndex(
            model_name='buyerorder',
            index=models.Index(fields=['gold_account', '-created_at'], name='buyer_order_gold_ac_7e9d76_idx'),
        ),
    ]
