# Generated by Django 6.0.8 on 2026-08-18 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=32, unique=True)),
                ('display_name_fa', models.CharField(max_length=100)),
                ('purity', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asset_types',
                'ordering': ['code'],
            },
        ),
    ]
